# Generated by Django 4.1.7 on 2023-02-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=50, verbose_name="Empresa")),
                (
                    "job_title",
                    models.CharField(max_length=50, verbose_name="Cargo na empresa"),
                ),
                (
                    "salary",
                    models.FloatField(
                        help_text="Exemplo: 1.500R$", verbose_name="Salário"
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Data de pagamento")),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.AlterField(
            model_name="person",
            name="age",
            field=models.IntegerField(verbose_name="Idade"),
        ),
    ]
