# Generated by Django 4.1.7 on 2023-02-28 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_enterprise_alter_person_age"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enterprise",
            old_name="company",
            new_name="name",
        ),
        migrations.AddField(
            model_name="enterprise",
            name="employment_contract",
            field=models.CharField(
                choices=[
                    ("estagio", "Estágio"),
                    ("pj", "PJ"),
                    ("clt", "CLT"),
                    ("aprendiz", "Aprendiz"),
                ],
                default="desempregado",
                max_length=50,
                verbose_name="Tipo de contrato",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="company",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company",
                to="account.enterprise",
            ),
        ),
    ]
