# Generated by Django 4.1.7 on 2023-02-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_rename_company_enterprise_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="employment_contract",
            field=models.CharField(
                choices=[
                    ("estagio", "Estágio"),
                    ("pj", "PJ"),
                    ("clt", "CLT"),
                    ("aprendiz", "Aprendiz"),
                    ("desempregado", "Desempregado"),
                    ("autonomo", "Autônomo"),
                ],
                default="desempregado",
                max_length=50,
                verbose_name="Tipo de contrato",
            ),
        ),
    ]
